apiVersion: v1
kind: Pod
metadata:
  name: myiis
  labels: 
    env: dev
    type: frontend
spec:
  containers:
    - image: microsoft/iis
      name: iis
      ports:
        - containerPort: 80
          name: http
