version: "3.4"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: classicmodels
      MYSQL_USER: vilas
      MYSQL_PASSWORD: vilas
#   ports: #This is the default
#     - "3306:3306"
    volumes:
     - ./db:/docker-entrypoint-initdb.d
#     - /home/docker/mysql-data:/var/lib/mysql

  web:
    build:
      context: ./tomcatApp
      dockerfile: Dockerfile
    environment:
      JDBC_URL: jdbc:mysql://db:3306/classicmodels?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: root
      JDBC_PASS: admin
    ports:
     - "80:8080"
    #volumes:
     #- ./tomcat/webapps:/usr/local/tomcat/webapps
    links:
      - db
