apiVersion: v1
kind: Service
metadata:
  name: frontendsvc
spec:
  selector:
    app: myfrontend
  type: NodePort
  ports:
  - port: 8080


---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myfrontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: myfrontend
  template:
    metadata:
      labels:
        app: myfrontend
    spec:
      containers:
      - image: vilasvarghese/k8sfrontend
        name: myfrontend
        ports:
        - containerPort: 8080
