apiVersion: v1
kind: Pod
metadata:
  name: winhostpath 
spec:
  containers:
    - name: wincontainer
      image: microsoft/iis 
      volumeMounts:
      - mountPath: C:/test-mnt
        name: test-vol
  volumes:
  - name: test-vol
    hostPath:
#######################################################
#Ensure to create a folder with this name on your worker node. This restriction is only for windows
###############################################################################
      path: C:/test-vol
