apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: "2023-02-25T04:46:43Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: elasticsearch-master
    name: elasticsearch-master-elasticsearch-master-0
    namespace: default
    resourceVersion: "3629"
    uid: 004b758c-ffee-44c7-8435-73ecbfe34faa
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100M
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: "2023-02-25T04:46:43Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: elasticsearch-master
    name: elasticsearch-master-elasticsearch-master-1
    namespace: default
    resourceVersion: "3638"
    uid: 8bb2854d-f458-43d6-a611-c87fb949ddc3
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100M
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: "2023-02-25T04:46:43Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: elasticsearch-master
    name: elasticsearch-master-elasticsearch-master-2
    namespace: default
    resourceVersion: "3647"
    uid: 98b8e8e8-222e-4176-92d6-651906310cd1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100M
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Pending
kind: List
metadata:
  resourceVersion: ""
