#kubectl create namespace quota-mem-cpu-example
#kubectl apply -f https://k8s.io/examples/admin/resource/quota-mem-cpu.yaml --namespace=quota-mem-cpu-example
#View detailed information about the ResourceQuota:

#kubectl get resourcequota mem-cpu-demo --namespace=quota-mem-cpu-example --output=yaml

apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi