apiVersion: v1
kind: Pod
metadata:
  name: mysecret-pod
spec:
  containers:
  - name: mypod
    image: microsoft/iis 
    volumeMounts:
    - name: foo
      mountPath: "C:/etc"
      readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: mysecret
