apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-22T01:02:26Z"
  name: elasticsearch
  namespace: elastic-stack
  resourceVersion: "1448"
  uid: 75b638d0-13d4-43d4-abd9-e51c01773517
spec:
  clusterIP: 10.108.76.224
  clusterIPs:
  - 10.108.76.224
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port1
    nodePort: 30200
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: port2
    nodePort: 30300
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    name: elastic-search
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}