docker-mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: root 
    MYSQL_DATABASE: book_manager 
    MYSQL_USER: admin 
    MYSQL_PASSWORD: admin 
#  ports:
#    - "3306:3306"
  volumes:
   - ./docker-compose-spring-boot/sql:/docker-entrypoint-initdb.d

web:
  image: tomcat:latest
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
    JDBC_URL: jdbc:mysql://docker-mysql:3306/mydb?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    JDBC_USER: admin 
    JDBC_PASS: admin 
  ports:
   - "80:8080"
  volumes:
   - ./docker-compose-spring-boot/target/:/usr/local/tomcat/webapps
  links:
    - docker-mysql 
