#examples of information recorded in annotations:
#	Declarative configuration layer. 
#	Build, release, or image information 
#		timestamps, release IDs, git branch, PR numbers, image hashes, and registry address.
#	Pointers to logging, monitoring, analytics, or audit repositories.
#	Client library or tool information that can be used for debugging purposes: for example, name, version, and build information.
#	User or tool/system provenance information, such as URLs of related objects from other ecosystem components.
#	Lightweight rollout tool metadata: for example, config or checkpoints.
#	Phone or pager numbers of persons responsible, or directory entries that specify where that information can be found, such as a team web site.
#	Directives from the end-user to the implementations to modify behavior or engage non-standard features.


apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80