#Create a new deployment named red with the nginx image and 2 replicas, and ensure it gets placed on the controlplane node only.

#Use the label key - node-role.kubernetes.io/control-plane - which is already set on the controlplane node.
#Name: red
#Replicas: 2
#Image: nginx
#NodeAffinity: requiredDuringSchedulingIgnoredDuringExecution
#Key: node-role.kubernetes.io/control-plane
#Use the right operator


apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: red
  name: red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: red
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: red
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            -  matchExpressions:
               - key: node-role.kubernetes.io/control-plane
                 operator: Exists
status: {}