apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "app"
    operator: "Exists"
#    value: "DBNode"
    effect: "NoSchedule"
##kubectl taint nodes kworker1 app=DBNode:NoSchedule
##kubectl taint nodes <node> <key1>=<value1>:NoSchedule
##kubectl taint nodes <node> <key1>=<value1>:NoSchedule- to remove taint

#Other options

#option1
#tolerationWithValue.yaml
