apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: delayed-volume-sc   #if this name is local-storage, then until pod get's bound, pv and pvc will not get bound.
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer